//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsAutoThemeSwitcherForWin10DarkMode.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VsAutoThemeSwitcherForWin10DarkMode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;Auto Theme Switcher for Win10 Dark Mode&quot; extension: 的本地化字符串。
        /// </summary>
        public static string Auto_Theme_Switcher_for_Win10_Dark_Mode_extension_ {
            get {
                return ResourceManager.GetString("Auto Theme Switcher for Win10 Dark Mode extension:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;Auto Theme Switcher for Win10 Dark Mode&quot; extension error: 的本地化字符串。
        /// </summary>
        public static string Auto_Theme_Switcher_for_Win10_Dark_Mode_extension_error_ {
            get {
                return ResourceManager.GetString("Auto Theme Switcher for Win10 Dark Mode extension error:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Theme: 的本地化字符串。
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception: 的本地化字符串。
        /// </summary>
        public static string Exception_ {
            get {
                return ResourceManager.GetString("Exception:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Theme: 的本地化字符串。
        /// </summary>
        public static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please go to &quot;Tools&quot; → &quot;Options&quot; → &quot;Auto Theme Switcher for Win10&quot; and check the settings. 的本地化字符串。
        /// </summary>
        public static string Please_go_to_Tools_Options_Auto_Theme_Switcher_for_Win10_and_check_the_settings_ {
            get {
                return ResourceManager.GetString("Please go to Tools Options Auto Theme Switcher for Win10 and check the settings.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registry value not found: 的本地化字符串。
        /// </summary>
        public static string Registry_value_not_found_ {
            get {
                return ResourceManager.GetString("Registry value not found:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify the light and dark themes for auto switch. 的本地化字符串。
        /// </summary>
        public static string SpecifyThemesForAutoSwitch {
            get {
                return ResourceManager.GetString("SpecifyThemesForAutoSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This extension requires Windows 10 Build 14393 or above. 的本地化字符串。
        /// </summary>
        public static string This_extension_requires_Windows_10_Build_14393_or_above_ {
            get {
                return ResourceManager.GetString("This extension requires Windows 10 Build 14393 or above.", resourceCulture);
            }
        }
    }
}
